version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 81:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - composer-volume:/var/www/php/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    working_dir: /var/www/html
#    command: 'php artisan serve --host 0.0.0.0'
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ptcs
      MYSQL_USER: ptcs
      MYSQL_PASSWORD: ptcs
    volumes:
      - ./docker/mysql/my.cnf:/etc/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - mysql-volume:/var/lib/mysql
    ports:
      - 3307:3306
#  node:
#    image: node:9
#    volumes:
#      - .:/app
#      - node-modules-volume:/app/node_modules
#    working_dir: '/app'
volumes:
  composer-volume:
  mysql-volume:
  node-modules-volume: